### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by RandomAltThing** [jose-vm/MoreToolsAddon#4]
Can you please make a tutorial (Or a github gist) oh how to add a block? My way is really messy but yours seems the most efficiency way. Maybe you could make an example add with 1 block added?

**Comment by RedstoneGunMade** [comment]
do not ask this things, deleted

**Comment by RandomAltThing** [comment]
Do you even know what you're doing? The issues section is for asking ***issues***. Issues can also mean ***help***. I'm asking for help with something related to this repository. You have no right to close this.

**Comment by RandomAltThing** [comment]
@jose-vm

**Comment by RedstoneGunMade** [comment]
but isnt for the mod, is a external help (this mod adds tools, no blocks)

**Comment by RandomAltThing** [comment]
Whoops, I was meant to say item.

**Comment by RedstoneGunMade** [comment]
and not needed (for now, needs to be fixed)

**Comment by RandomAltThing** [comment]
Not needed? And tbh, you don't deserve collaborator. You haven't made a single commit. Or are you too stupid to find the "Add file" button?

**Comment by RedstoneGunMade** [comment]
im working on PE like PC, so i cant contribute for now

**Comment by RedstoneGunMade** [comment]
another addon

**Comment by RandomAltThing** [comment]
Alright then. Screenshots?

**Comment by minecraftmuse3** [comment]
I agree with @RandomAltThing. This is an issue, and @RedstoneGunMade You don't need to close it. @RandomAltThing, ask me for help if you need it ;)

**Comment by jose-vm** [comment]
I can also help you @RandomAltThing. @RedstoneGunMade gets pretty upset sometimes :P

**Comment by minecraftmuse3** [comment]
Lol @jose-vm

**Comment by RedstoneGunMade** [comment]
sorry ;( 
If im a bad person sorry ;(
